#!/bin/bash
clear
echo ""

tput setaf 2 ; tput bold ; echo "BADVPN: UDP - Script By @MajinBoo" ; tput sgr0
tput setaf 2 ; tput bold ; echo "Exclusivo para CentOs" ; tput sgr0

echo "$(tput bold) ESCOLHA UMA OPÇÃO: $(tput sgr0)"

echo ""

echo "1. CentOs de 64 bits"

echo "2. CentOs de 32 bits"

echo "3. Screen BADVPN: UDP"

echo "4. Sair do Script"

echo ""

echo -n "Qual a opção desejada? "

read opcao

case $opcao in

1)
clear
echo "$(tput bold) BADVPN: UDP - Script By @MajinBoo $(tput sgr0)" 

wget -O /usr/bin/badvpn-udpgw "https://raw.github.com/srbuu/badudp/master/badvpn-udpgw64" 1>/dev/null 2>/dev/null 

echo "screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300" >> /etc/rc.local 1>/dev/null 2>/dev/null 

echo "screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300" >> /etc/rc.d/rc.local

chmod +x /usr/bin/badvpn-udpgw 1>/dev/null 2>/dev/null 

screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300 1>/dev/null 2>/dev/null 

echo "$(tput bold) BADVPN: UDP CONFIGURADO COM SUCESSO. Script By @MajinBoo. $(tput sgr0)"

;;

2)
clear
echo "$(tput bold) BADVPN: UDP - Script By @MajinBoo $(tput sgr0)" 
wget -O /usr/bin/badvpn-udpgw "https://raw.github.com/srbuu/badudp/master/badvpn-udpgw"

echo "screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300" >> /etc/rc.d/rc.local

echo "screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300" >> /etc/rc.d/rc.local

chmod +x /usr/bin/badvpn-udpgw 1>/dev/null 2>/dev/null 

screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300 1>/dev/null 2>/dev/null 

echo "$(tput bold) BADVPN: UDP CONFIGURADO COM SUCESSO. Script By @MajinBoo. $(tput sgr0)"

;;
3)
echo "$(tput bold) ABRINDO SESSÃO SCREEN BAD-UDP. $(tput sgr0)"

screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300 1>/dev/null 2>/dev/null 

echo "$(tput bold) Script By @MajinBoo. $(tput sgr0)"

;;

4)
echo "$(tput bold) saindo do Script.... $(tput sgr0)"
exit
;;
esac